import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useQuery } from '@apollo/client'
import GET_MISSIONS from '../lib/apollo/queries/getMissions'


const Home: NextPage = () => {
  let {loading, data} = useQuery(GET_MISSIONS);  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>SpaceX Missions</h1>
        <ol>
          {
            loading && <h1>Loading SpaceX Missions ...</h1>
          }
          {
            !loading && data && data.missions.map((mission:any) => (
              <li key={mission.id}>
                <h2>Manufacturers : {mission.manufacturers.join(", ")}</h2>
                <p><span style={{color: 'tomato'}}>Name</span> : {mission.name}</p>
                <p><span style={{color: 'tomato'}}>Twitter</span> : {mission.twitter}</p>
                <p><span style={{color: 'tomato'}}>Website</span> : {mission.website}</p>
                <p><span style={{color: 'tomato'}}>Wikipedia</span> : {mission.wikipedia}</p>
              </li>
            ))
          }
        </ol>
      </main>
    </div>
  )
}

export default Home
