import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import axios from 'axios';
import Link from 'next/link';

const Home: NextPage = () => {
  const [users, setUsers] = useState<null|any[]>(null);
  const [loading, setLoading] = useState<boolean>(true);

  const getUsers = async () => {
    const usersResponse = await axios.get(`${process.env.API_ENDPOINT}/users`);
    setUsers(usersResponse.data);
  }

  useEffect(() => {
    getUsers();
    setLoading(false);
  }, [])
  
  return (
    <div>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {
          loading && <p>Loading Users ...</p>
        }
        {
          !loading && users && (
            users.length > 0 ? (
                <ul>
                  {
                    users.map((user : any) => (
                      <li key={user.id}>
                        <Link href={`/users/${user.username}`} passHref>
                          <a>{user.username}</a>
                        </Link>
                      </li>
                    ))
                  }
                </ul>
            ) : (
              <p>No User Found</p>
            )
          )
        }
      </main>
    </div>
  )
}

export default Home
