import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import client from '../lib/apollo';
import GET_ROCKETS from '../lib/apollo/queries/getRockets';

interface Rocket {
  id: string
  name: string
}

interface RocketsInterface {
  loading: boolean,
  data: {
    rockets : Rocket[]
  }
}

export const getStaticProps : GetStaticProps = async () => {
  const { loading, data } = await client.query<RocketsInterface>({ query: GET_ROCKETS });
  return {
    props : {
      loading,
      data
    }
  }
}

const Home: NextPage<RocketsInterface> = ({loading, data}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>SpaceX Rockets List</h1>
        {
          loading && <h1>Loading Rockets ...</h1>
        }
        <ol>
          {
            !loading && data && data.rockets.map((rocket : Rocket) => (
              <li key={rocket.id}>
                <Link href={`/rockets/${rocket.id}`} passHref>
                  <a>{rocket.name}</a>
                </Link>
              </li>
            ))
          }
        </ol>
      </main>
    </div>
  )
}

export default Home;