import React from 'react'
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';

const Posts:NextPage = () => {
  return (
    <div className={styles.container}>
        <Head>
        <title>Page Route Variables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h1>Nested Routes <br /> Posts</h1>
            <ul>
                <li className={styles.li}><a href="/posts/02-01-22/next-js">Next Js</a></li>
                <li className={styles.li}><a href="/posts/08-31-22/react-js">React Js</a></li>
                <li className={styles.li}><a href="/posts/05-15-22/gatsby-js">Gatsby Js</a></li>
                <li className={styles.li}><a href="/posts/11-24-22/javascript">JavaScript</a></li>
            </ul>
        <a className={styles.btn} href="/">Goto Homepage</a>
        <a className={styles.btn} href="/contact-us">Goto Contact Us Page</a>
        </main>
        <footer className={styles.footer}>
            <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
            >
                Powered by{' '}
                <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
            </a>
        </footer>
    </div>
  )
}

export default Posts;