import type { NextPage } from 'next'
import { useContext } from 'react'
import Head from 'next/head'
import Stopwatch from '../components/Stopwatch'
import styles from '../styles/Home.module.css'
import globalContext from '../context/global/globalContext'

const Home: NextPage = () => {
  const { resetTimer } = useContext(globalContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stopwatch />
        <button onClick={resetTimer}>Reset</button>
      </main>
    </div>
  )
}

export default Home
