import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homepage}>
        <h1 className={styles.title}> Welcome to the CSS Modules example </h1>
        <button className="Button">Simple Button</button>
        <button className={styles.button_default}>Default Button</button>
        <button className={styles.button_success}>Success Button</button>
        <button className={styles.button_danger}>Danger Button</button>
      </div>
    </div>
  )
}

export default Home
