import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { incrementByAmount } from '../store/reducers/counterSlice';
import { wrapper } from '../store/store';
import Counter from '../components/Counter';

export const getStaticProps : GetStaticProps = wrapper.getStaticProps(store => async () => {
    store.dispatch(incrementByAmount(10));
    return { props: {} }
})

const StaticSideCounter: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Counter />
      </main>
    </div>
  )
}

export default StaticSideCounter;
