import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '../store/reducers';
import { increment, decrement } from '../store/reducers/counter/counterSlice';

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { count } = useSelector((state : RootState) => state.counter);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Counter : {count}</p>
        <button onClick={() => dispatch(increment())}>+</button>
        &nbsp;&nbsp;
        <button onClick={() => dispatch(decrement())}>-</button>
      </main>
    </div>
  )
}

export default Home
