import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios';
import Link from 'next/link';

export const getStaticProps:GetStaticProps = async () => {
  // Here we will do REST request
  const users = await axios.get('https://jsonplaceholder.typicode.com/users');
  return {
    props: {
      users: users.data,
    }
  }
}

const Home: NextPage<{users : any}> = ({users}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>REST Request on SSG</h1>
        <ul>
          {
            users.map((user:any) =>
              <li key={user.id}>
                <Link
                  href={`/users/${user.username}`}
                  passHref
                >
                  <a>{user.username}</a>
                </Link>
              </li>
            )
          }
        </ul>
      </main>
    </>
  )
}

export default Home
