import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Stopwatch from '../components/Stopwatch'
import styles from '../styles/Home.module.css'
import { useContext } from 'react'
import { TimestampState } from '../components/context/types'
import stopwatchContext from '../components/context/stopwatchContext'

const Home: NextPage = () => {
  const { setTimestamp } = useContext<TimestampState>(stopwatchContext)

  const reset = () => setTimestamp({timestamp : { hours : 0, minutes : 0, seconds : 0}})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stopwatch />
        <button onClick={reset}>Reset</button>
      </main>
    </div>
  )
}

export default Home
