import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{color: 'dodgerblue'}}>About Page</h1>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Necessitatibus, cupiditate non veniam soluta distinctio ipsam provident vitae voluptas dignissimos ea, vero voluptatem vel sapiente culpa delectus quas error doloremque ad iste est. Optio laboriosam quidem facere quod quisquam ea, ullam culpa alias dolores eum fugiat architecto! Et tempora tenetur, sit ab porro cupiditate ut molestias distinctio explicabo laborum libero. Cumque, repellendus. Odio cumque tenetur officiis corporis eos distinctio expedita optio ut beatae magni. Aperiam ex nostrum eos, impedit quisquam voluptates dolore cumque eum molestias necessitatibus praesentium similique, consequuntur in rerum sequi ipsa corrupti qui odio veniam? Praesentium dignissimos itaque temporibus.</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default About
